# Generated by Django 2.2.15 on 2020-08-13 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_documentos_pertencente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='pertencente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='colaboradores.Colaborador'),
            preserve_default=False,
        ),
    ]
