# Generated by Django 2.2.15 on 2020-08-13 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0004_auto_20200813_1552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colaborador',
            options={'verbose_name_plural': 'Colaboradores'},
        ),
    ]
